config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  resources :users, only: [:show]
  resources :tweets do
    resources :comments, only: [:create, :destroy ]
    member do
      post :reply
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  validates :text, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  mount_uploader :picture, PictureUploader
  validates :description, :picture, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
 has_many :replies, class_name: "Comment", foreign_key: :reply_id, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets,dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!
   before_action :configure_permitted_parameters, if: :devise_controller?  
  
  def after_sign_in_path_for(resource)
    root_path #　ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
  end
  
  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def create
  @tweet=Tweet.find_by(id: params[:tweet_id])
  @comment=Comment.new(comment_params)
  @comment.user_id=current_user.id
  @comment.tweet=@tweet 
  if @comment.save
    flash[:notice] = "投稿しました"
  else
    Rails.logger.error @comment.errors.full_messages.join('')
    flash[:alert] = "投稿できませんでした"
  end
  redirect_to tweet_path(@tweet), method: :get
end

def reply
  @tweet=Tweet.find_by(id: params[:tweet_id])
  @comment=@tweet.comments
  @reply=@comment.new(comment_params)
  
  @reply.user_id=current_user.id
  @reply.tweet=@tweet
  @reply.reply_id=@tweet
  
   if @reply.save
    flash[:notice]= "コメントしました"
   else
    flash[:alert]="コメント出来ませんでした。"
   end
  redirect_to tweet_path(@tweet), method: :get
end

def destroy
  @tweet=Tweet.find_by(id: params[:tweet_id])
  @comment=Comment.find_by(id: params[:tweet_id])
  @comment.destroy
  flash[:notice] = "削除しました"
  redirect_to controller: "tweets", action: "show"
end

private
  def comment_params
    params.require(:comment).permit(:user_id, :tweet_id, :text, :reply_id)
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
   before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @tweets=Tweet.all
  end
  
  def new
    @tweet=Tweet.new
  end
  
  def show
    @tweet=Tweet.find_by(id: params[:id])
    @comments=@tweet.comments
    @comment=Comment.new
  end
   
  def create
    @tweet=current_user.tweets.new(tweet_params)
    @tweet.save
    flash[:notice] = "投稿しました"
    redirect_to root_path
  end
  
  
  def edit
    @tweet=Tweet.find_by(id: params[:id])
  end
  
  def update
    @tweet=Tweet.find_by(id: params[:id])
    @tweet.update(tweet_params)
    
    if @tweet.save
    flash[:notice] = "編集しました"
    redirect_to root_path
    else
      flash[:alert]="画像投稿は必須です。"
    redirect_to new_tweet_path
    end
    
  end
  
  def destroy
    @tweet=Tweet.find_by(id: params[:id])
    @tweet.destroy
    flash[:notice] = "削除しました"
    redirect_to root_path
  end
  
  private
  def tweet_params
    params.require(:tweet).permit(:description, :picture, :user_id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!, except: [:show]
   
   def show
    @user=User.find_by(id: params[:id])
   end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Sample</a>
    </div>
    <div class="collapse navbar-collapse">
      <p class="navbar-text pull-right">
  <% if user_signed_in? %>
     <strong><%= current_user.name %>さんがログイン中</strong>.
    <%= link_to 'アカウント編集', edit_user_registration_path, class: 'nav-link' %> |
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link'  %>
  <% else %>
    <%= link_to "新規登録", new_user_registration_path, class: 'nav-link'  %> |
    <%= link_to "ログイン", new_user_session_path, class: 'nav-link'  %>
  <% end %>
</p>
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "投稿する", new_tweet_path %></li>
      </ul>
    </div>
  </div>
  
  <% if notice %>
　　<p><%= notice %></p>
    <% end %>
    <% if alert %>
     <p><%= alert %></p>
  <% end %>
    
   <div class="container pages">
    <%= yield %>
  </div>
  
  </body>
  
  <footer>
  
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</html>

app/views/tweets/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      投稿が完了しました。
    </h3>
    <%= link_to "トップに戻る", root_path %>
  </div>
</div>

app/views/tweets/destroy.html.erb
<h1>削除しました</h1>
<%= link_to "トップに戻る", root_path %>

app/views/tweets/edit.html.erb
<div class="container">
  <%= form_for @tweet do |f| %>
  
  <h1>編集する</h1>
  
 <div class="field">
   <p>コメント</p>
   <%= f.text_field :description %>
 </div></br>
 
 <div class="field">
   <%= f.file_field :picture %></br>
 </div>
 
 <%= f.submit "投稿" %>
 <% end %></br>
 <%= button_to "削除", tweet_path(@tweet.id), method: :delete, data: { confirm: '削除しますか？' } %>
 
 </div>
 
 

app/views/tweets/index.html.erb
<div class="container" >
  <% @tweets.each do |f| %>
  <%= link_to f.user.name, user_path(f.user.id), method: :get %>
    </br><%= f.description %></br>
    <%= image_tag (f.picture_url) %></br>
    
    <% if user_signed_in? && current_user.id==f.user.id %>
     <%= link_to "編集", edit_tweet_path(f)%>
    <% end %>
    
    <%= link_to "詳細",tweet_path(f),method: :get %></br></br>
  <% end %>
</div>

app/views/tweets/new.html.erb
<div class="container">
  <%= form_for @tweet do |f| %>
  
  <h1>投稿する</h1>
  
 <div class="field">
   <p>コメント</p>
   <%= f.text_field :description %>
 </div></br>
 
 <div class="field">
   <%= f.file_field :picture %></br>
 </div>
 
 <%= f.submit "投稿" %>
 
 </div>
 
 <% end %>

app/views/tweets/show.html.erb
<div class="container" >
     <%= link_to @tweet.user.name, user_path(@tweet.user.id), method: :get %>
    </br><%= @tweet.description %></br>
    <%= image_tag (@tweet.picture_url) %></br></br>
    
    <% @comments.each do |c| %>
      <%= link_to c.user.name, user_path(c.user.id), method: :get %>
      <%= c.text %>
      <% if user_signed_in? && c.user_id==current_user.id %>
        <%= button_to "削除する", tweet_comment_path(c), method: :delete, data: { confirm: '削除しますか？' } %>
      <% end %></br></br>
    <% end %>
    
    <% if user_signed_in? %>
      <%=form_for [@tweet, @comment] do |f| %>
      <%= f.text_field :text %>
      <%= f.submit "コメントする" %>
      <% end %>
    <% end %>
    
    <%= link_to "戻る", root_path %>
</div>

app/views/tweets/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      編集が完了しました。
    </h3>
    <%= link_to "トップに戻る", root_path %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container" >
<h1>名前 : <%= @user.name %>さんのページ</h1>
<h3>投稿一覧</h3>

 <% @user.tweets.each do |u| %>
   <%= u.description %><br>
   <%= image_tag (u.picture_url) %><br>
   
    <% if user_signed_in? && current_user.id==u.user.id %>
     <%= link_to "編集", edit_tweet_path(u)%>
    <% end %>
    
    <%= link_to "詳細",tweet_path(u),method: :get %></br></br>
<% end %>
 
</div>